blank_issues_enabled: true
contact_links:
  - name: Qiskit.org issues
    url: https://github.com/Qiskit/qiskit.org/issues/new/choose
    about: Please open issues related to the Qiskit.org website here
  - name: Qiskit Textbook issues
    url: https://github.com/Qiskit/platypus/issues/new/choose
    about: Please open issues related to the Qiskit Textbook here
